services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartlearn_app
    volumes:
      - .:/var/www
    depends_on:
      - db
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    container_name: smartlearn_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: smartlearn
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: smartlearn
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
